### ISSUE TITLE
The equivalent of "control right click" is unclear for macOS

### ISSUE THREAD

**Issue by mhucka** [panqec/panqec#31]
I'm enjoying <https://gui.quantumcodes.io/>, but am experiencing a problem with mouse clicks. MacOS users with a typical trackpad (mine is the [Magic Trackpad](https://www.apple.com/shop/product/MK2D3AM/A/magic-trackpad-white-multi-touch-surface)) would achieve the equivalent of Windows' "right click" by using "control click". The problem I'm running into is that gui.quantumcodes.io uses both "control left click" and "control right click", and they seem to do the same action on macOS.

Is there a setting in the control panel that controls this behavior? Alternatively, is there something else I should do?

**Comment by artix41** [comment]
Hi! Thanks for your comment. I actually recently got a Mac and experienced the same issue, so I've changed the controls in my branch to ctrl-click for X errors and shift-click for Z errors, which indeed improves the experience on Mac! I will update the website asap with this change, thanks for reminding me! In the meantime, you can try clicking with two fingers (it's the default trackpad equivalent to right-click on Mac).

**Comment by mhucka** [comment]
Thanks! I'll give it a try.

**Comment by artix41** [comment]
Fixed by #32
I've also updated the website. Thanks again for raising the issue! :)
